services:
  python:
    image: my-python-service
    build:
      context: ./src
    ports: 
      - 8080:80

  ollama:
    image: ollama/ollama:latest
    ports: 
      - 11434:11434
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_model_store:/root/.ollama

volumes:
  ollama_model_store: