services:
  python:
    #image: my-python-service
    image: semtech/mu-python-template:2.0.0-beta.2
    environment:
      MODE: "development"
    volumes:
      - ./src/:/app
    ports: 
      - 8080:80

  ollama:
    image: ollama/ollama:latest
    ports: 
      - 11434:11434
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_model_store:/root/.ollama

volumes:
  ollama_model_store: