services:
  python:
    image: lpdc-ai-service-group5
    build:
      context: ./src
    #image: semtech/mu-python-template:2.0.0-beta.2
    environment:
      MODE: "development"
      OLLAMA_HOST: ollama:11434
    volumes:
      - ./src/:/app
    ports: 
      - 8080:80

  ollama:
    image: ollama/ollama:latest
    ports: 
      - 11434:11434
    restart: always
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ./models:/root/.ollama/models
      #- ollama_model_store:/root/.ollama

volumes:
  ollama_model_store: 
